apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-hub
  labels:
    app: connect-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connect-hub
  template:
    metadata:
      labels:
        app: connect-hub
    spec:
      containers:
      - name: connect-hub
        image: skylabworld/connect-hub
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
